### ISSUE TITLE
How to get TP-LINK M7200 modules list to access the different router features

### ISSUE THREAD

**Issue by Techjobis** [mehmetbeyHZ/tp-link-m7200-api#2]
Hello,

I would like to know how can I get the list of modules to use to call the different router features. Your project only specifies the createLoginTokens, authentication and rebootDevice api modules. I would like to know if you have the list of other modules like the sms and ussd module feature that I can use to access them from the app. Thank you.

**Comment by mt-ks** [comment]
Hello, I have approved a pull request, Please check it #1

**Comment by Techjobis** [comment]
@mehmetbeyHZ Thank you for your swift response. Let me check it out. Thank you again.

**Comment by Techjobis** [comment]
Hello @mehmetbeyHZ, Thank you for approving the PR. Can you please help me with the list of modules and actions that I can use to access the tp-link m7200 ussd feature?

**Comment by Techjobis** [comment]
Hello @mehmetbeyHZ , I have just confirmed that module and action for ussd feature is there. Thanks for the help. Just wanted to ask how we can pass the content of the ussd?
